from rsf.proj import *

import sys
sys.path.append("../utility")
import subprocess
import debug_module
debug_module.doDebugOrNot(ARGUMENTS)

file_to_fetch = "shots.hh"
directory_to_fetch_from = "Amoco"
rsf_file = "shots"

flow_parameters = dict(rscale=.0003048,
                       x_position_min_in_km = 11)
result_parameters = dict(bias=1.9,
                         screenwd=18,
                         shot_position_in_km=18.2)

           
            # Fetch Files from repository
Fetch(file_to_fetch,directory_to_fetch_from)

            # Convert Files to RSF
Flow(rsf_file,file_to_fetch, 
     '''dd form=native | 
        put  label1=time 
             label2=offset 
             label3=shot 
             unit1=s 
             unit2=km 
             unit3=km | 
        scale rscale=%(rscale)d''' % flow_parameters)

            # Plotting Section
Result('zeroOne',rsf_file,
       '''window $SOURCE  
                 min2=0 
                 max2=5
                 min3=%(shot_position_in_km)f
                 max3=%(shot_position_in_km)f 
                 size3=1 | 
         grey  pclip=96 
               color=I 
               screenratio=1.5 
               gainpanel=a 
               title=zeroOne 
               labelsz=6''' % result_parameters)

# Result('zeroTwo',rsf_file,
#        '''window $SOURCE 
#                  min2=0 
#                  max2=0 
#                  size2=1 
#                  min3=10.6 | 
#           grey  pclip=97 
#                 color=I 
#                 screenratio=1.5 
#                 gainpanel=a 
#                 label2=Position 
#                 label1=Time 
#                 title= 
#                 label3=  
#                 unit2=km 
#                 unit1=s
#                 labelsz=6''')
# 
# Result('shot40',rsf_file,
#        '''window $SOURCE  
#                  min3=14 
#                  max3=14 
#                  size3=1 | 
#           grey  pclip=99 
#                 color=I 
#                 gainpanel=a 
#                 wantframenum=y  
#                 unit1=s 
#                 label1=Time
#                 label2=Offset 
#                 unit2=km 
#                 label3=Shot 
#                 unit3=km 
#                 title=
#                 screenratio=1.35 
#                 labelsz=3''')



End()
