from rsf.proj import *

def igrey(custom):
    return '''
    grey color=j labelsz=5 titlesz=6 %s
    ''' %(custom)

def grey(custom):
    return '''
    grey labelsz=5 titlesz=6 %s
    ''' %(custom)

def srcgen(par):
    dtt=0.0001
    fac=par['dt']/dtt
    ntt=(par['nt']-1)*fac+1
    ktt=(par['srcbgn']-1)*fac+1

    #i/(2*phi)=i/(2|omega|)=i/2 * (hilb) [(int)source] 

    Flow('source1',None,
         '''
         spike n1=%d d1=%g k1=%d |
         ricker1 frequency=%g
         '''%(ntt,dtt,ktt,par['frq']))
    Flow('realsrc','source1','math "output=0"')
    Flow('imagsrc','source1','envelope hilb=y order=500 | halfint | halfint | math output="input/2" ')
    
    Flow('csource1','realsrc imagsrc','cmplx ${SOURCES[1]}')
    Flow('csource','csource1','window j1=%d'% fac)
    return 'csource'


Flow('vel','vel.asc','echo in=$SOURCE n1=398 n2=161 data_format=ascii_float | dd form=native | put d1=12.5 d2=12.5 o1=0 o2=0 | transp plane=12 | expand top=30 left=0 right=0 bottom=0')

Result('vel','grey allpos=y color=j title="BP velocity model" ')

Flow('ref','vel',
     '''depth2time velocity=$SOURCE nt=2000 dt=0.004 |
     ai2refl | ricker1 frequency=20 |
     time2depth velocity=$SOURCE
     ''')
Flow('iref','vel',
     '''depth2time velocity=$SOURCE nt=2000 dt=0.004 |
     ai2refl | ricker1 frequency=20 | envelope hilb=y order=500 |
     time2depth velocity=$SOURCE
     ''')
Flow('cref','ref iref','cmplx ${SOURCES[1]}')

par = {
    # model pars
    'nx' :  398,    # velocity model length 
    'nz' :  191,    # velocity model depth
    'nt' :  3001,   # record time length
    'dx' :  12.5,   # sampling in x
    'dz' :  12.5,   # sampling in z
    'dt' :  0.001,  # sampling in time
    'labelx': "Distance",
    'labelz': "Depth",
    'unitx' : "m",
    'unitz' : "m",
    'shtbgn': 200, # 1 imaged shot starting location on mesh
    'shtend': 200, # 398 shot ending location on mesh 
    'sintv' : 26,    # shot interval on mesh
    'spz'   : 5,    # shot depth on mesh
    'gpz'   : 5,    # receiver depth on mesh
    'gpl'   : 150,  # receiver length of single shot
    'snpint': 1,    # snapshot interval
    'pad1'  : 1,    # fft pading on the first axis
    # abc parameters 
    'top'   : 30,  # padding length
    'bot'   : 30,
    'lft'   : 30,
    'rht'   : 30,
    'dcz'   : 0.01, # decay coefficient
    'dcx'   : 0.01,
    #source
    'srcbgn'  : 50, # source begin time
    'frq'     : 22.5  # peak frequency of ricker wavelet (in Hz)
}

Fsrc  = srcgen(par)


Ffvel = 'vel'
Fbvel= 'bvel'
Fimg = 'img'
Ffvelabc = Ffvel+'x'
Fbvelabc = Fbvel+'x'
Ffft = 'fft'
Fref = 'cref'
Fleft = 'left'
Fright = 'right'
Ffleft = 'fleft'
Ffright = 'fright'
Fbleft = 'bleft'
Fbright = 'bright'
Ftmpwf =  'tmpwf'
Ftmpbwf = 'tmpbwf'
Frcd = 'shots'

Flow(Fbvel, Ffvel, 'smooth rect1=3 rect2=3 repeat=2')

for m in [Ffvel,Fbvel]:
    ext  = m+'x'
    Flow(ext,m,
         '''
         expand left=%(lft)d right=%(rht)d 
                top=%(top)d  bottom=%(bot)d
         '''%par)
# Lowrank decomposition
Flow(Ffft,Ffvelabc,'rtoc | fft3 axis=1 pad=1 | fft3 axis=2 pad=1')

Flow([Ffright,Ffleft],[Fbvelabc,Ffft],
     '''
      cisolr2abc seed=2010 npk=50 eps=1.e-4 dt=%(dt)g
      fft=${SOURCES[1]} left=${TARGETS[1]}
      nbt=%(top)d nbb=%(bot)d nbl=%(lft)d nbr=%(rht)d 
      ct=%(dcz)g cb=%(dcz)g cl=%(dcx)g cr=%(dcx)g
     '''%par)

Flow([Frcd, Ftmpwf],[Fref,Ffvelabc,Ffleft,Ffright,Ffleft,Ffright,Fsrc],
     '''
      sfmpirtmop input=$SOURCE output=$TARGET tmpwf=${TARGETS[1]}
      vel=${SOURCES[1]} left=${SOURCES[2]} right=${SOURCES[3]}
      leftb=${SOURCES[4]} rightb=${SOURCES[5]} src=${SOURCES[6]} 
      verb=y pad1=1 adj=n roll=n
      shtbgn=%(shtbgn)d shtend=%(shtend)d shtint=%(sintv)d
      spz=%(spz)g gpz=%(gpz)g gpl=%(gpl)g snapinter=%(snpint)d
      top=%(top)d bot=%(bot)d lft=%(lft)d  rht=%(rht)d
      rectz=2 rectx=2 repeat=1 srctrunc=0.4
      wantwf=n wantrecord=y illum=n
     '''%par,stdin=0,stdout=0,np=1 )

# ---------------------------------------------------------------

End()

# <shots.rsf sfcconjgrad ./lsrtm2.sh mod=img.rsf src=csource.rsf vel=velx.rsf left=fleft.rsf right=fright.rsf leftb=bleft.rsf rightb=bright.rsf verb=n pad1=1 roll=n shtbgn=1 shtend=398 shtint=5 spz=5 gpz=5 gpl=0 snapinter=1 top=30 bot=30 lft=30 rht=30 rectz=2 rectx=2 repeat=1 srctrunc=0.4 wantwf=n wantrecord=y illum=n roll=n > kinv10.rsf niter=10