from rsf.proj import *

import sys
sys.path.append("../utility")
import subprocess
import debug_module
debug_module.doDebugOrNot(ARGUMENTS)

file_to_fetch = "velmodel.hh"
directory_to_fetch_from = "Amoco"
flow_parameters = dict(rscale=64,
                       x_position_min_in_km = 11)
result_parameters = dict(bias=1.9,
                         screenwd=18)

            # Fetch Files from repository
Fetch(file_to_fetch,directory_to_fetch_from)

            # Convert Files to RSF
Flow('velmodel_dd_scale',
     file_to_fetch, 
     ''' dd form=native | \
         scale rscale=%(rscale)d | \
         put unit1=km \
             unit2=km \
             label1='Depth' \
             label2='Position' \ 
             title='Velocity Model' \                     
    ''' %flow_parameters)

Flow('velmodel_window',
     'velmodel_dd_scale',
     '''window min2=%(x_position_min_in_km)f\
               squeeze=y \
               verb=y \
     ''' %flow_parameters)

Result('velmodel_window',
       '''
       grey  scalebar=y barreverse=y
       color=j allpos=y bias=%(bias)f
       screenwd=%(screenwd)f 
       barlabel=" " barunit=km/s
       title="Amoco Velocity Model"
       labelsz=4 titlesz=6
       wheretitle=t
       ''' % result_parameters)

End()
