from rsf.proj import *
import os
import sys
sys.path.append("/home/mlai/geo/mlai/Rickett2003/PaperResults/Madagascar/utility")

from subprocess import call
import subprocess
import debug_module
debug_module.doDebugOrNot(ARGUMENTS)

second_rsf = 'individual_gain_data_by_trace_time.rsf'
second_rsf_with_header = os.path.splitext( os.path.basename(second_rsf))[0] + '_with_header' + '.rsf'
second_rsf_with_header_vpl = os.path.splitext( os.path.basename(second_rsf_with_header))[0] +  '.vpl'     
side_by_side_vpl = os.path.splitext( os.path.basename(second_rsf))[0] + '_sidebyside' + '.vpl'
side_by_side_pdf = os.path.splitext( os.path.basename(side_by_side_vpl))[0] + '.pdf'

first_rsf = 'original_data.rsf'
first_rsf_vpl = os.path.splitext( os.path.basename(first_rsf))[0] +  '.vpl'
        
 
        #add in header information
parameters = dict(
           d1=0.002,
           o1=0.002,
           label1='Time', 
           unit1='s',
           d2=0.05, 
           o2=-2,  
           label2='Offset',   
           unit2='km',
           title_second='(b)Individual gain for each trace',
           title_first='(a)Original data')
Flow(second_rsf_with_header,
     second_rsf,
     '''
     put d1=%(d1)g o1=%(o1)g label1=%(label1)s unit1=%(unit1)s 
         d2=%(d2)g o2=%(o2)g label2=%(label2)s unit2=%(unit2)s 
     ''' % parameters)
        
        #generate raster plot
Flow(second_rsf_with_header_vpl,
     second_rsf_with_header,
     '''
     grey title='%(title_second)s'
     ''' % parameters)

Flow(first_rsf_vpl,
     first_rsf,
     '''
     grey title='%(title_first)s'
     ''' % parameters)

        #generate side by side plot
Plot(side_by_side_vpl,
      first_rsf_vpl + ' ' + second_rsf_with_header_vpl,
      'SideBySideAniso')

#call("vpconvert %s format=pdf" % side_by_side_vpl)    

End()